language: python

python:
  - "2.7"

env:
  - TOXENV=django14
  - TOXENV=django15
  - TOXENV=django16

script:
  - tox

install:
  - pip install tox
  - pip install factory_boy
  - pip install -e .

deploy:
  provider: pypi
  user: iwoca
  password:
    secure: thHbKk8nvBJzM2QwTMnQFFHk93riUt7fnOwH8DgEe2yG8yKvI0yzZ+Kp6ffkt80gLAGW9Na6B7MzBwnG4cqK6KMGHASgpWfRVTLqHDKv1zNcivTjJa2dabpzAyF8uIwBdp3/sy14bwV7ZiVmm1i1m/Ku45dwTe32qoiPw+b1pRw=
  on:
    tags: true
    branch: master
